version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: infrastructure/docker/api.dockerfile
    image: api
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./backend/configs:/app/configs:ro
    depends_on:
      - scraping-service

  scraping-service:
    build:
      context: .
      dockerfile: infrastructure/docker/scraping.dockerfile
    image: scraping-service
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - ./backend/configs:/app/configs:ro